version: '3'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
      - ./php-config:/etc/apache2/conf-available

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_test
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
